### ISSUE TITLE
Hello and thanks!

### ISSUE THREAD

**Issue by duelist-X** [riQQ/MtgaProto#7]
Hello, I'm doing a little [hacking](https://github.com/duelist-X/MTGate) on MTGA, and was much puzzled by the protobuf thing until I found this repo. So I'm here to say thank you. I'm also wondering how you make use of the proto, and maybe our projects can benefit from each other.

**Comment by riQQ** [comment]
Hey, happy to hear that it helped you and interesting to hear about your use case.

I wrote this to support the main developer of mtgatool: https://github.com/mtgatool/mtgatool-desktop. 
The proto is used here: https://github.com/mtgatool/mtgatool-shared/tree/master/src/proto

I haven't heard of or seen any other projects using it so far.

**Comment by duelist-X** [comment]
I've been using Untapped, and I don't know how such tools get the information. I once heard they parsed log files iirc. So mtgatool uses it as a format specification to record the information?

**Comment by duelist-X** [comment]
It's really surprising to see such an interesting project around MTGA. Its connection and popularity is poor here and I can't find a better way to play it.

**Comment by Manwe-777** [comment]
Hi @duelist-X , dev of mtgatool here! We use MtgaProto mostly as a type safety within our development enviroment (react/typescript), it helps us know if some part of the logs specifications have changed when MTGA gets updated, in the best scenario we catch the diff and update all of our logs parsing accordingly. Some times we found really interesting types added to the client before a release was made ;)

However, lately we have been having issues where MTGA removes data from the logs entirely and we have to rely on memory reading instead using a [daemon](https://github.com/frcaton/mtga-tracker-daemon). This helps us get all the info that is not on the logs like collection data, and we use the protobuf thats still on the logs mostly for the GRE (client-server comms when playing a game)

**Comment by riQQ** [comment]
Untapped and mtgatool use log parsing and process memory reading as not all of the information is in the logs. Mtgatool's process memory reading is open source and can be found here:
https://github.com/frcaton/mtga-tracker-daemon

**Comment by duelist-X** [comment]
OK I see. It's very impressive to make something so fit along with the game UI simply by parsing the log. Since the connection is my main concern and I'm not promoting my stuff to others anyway, I'm using a man-in-the-middle server by mitmproxy to extract the connection protocol, a code inspect tool to modify the DLL, and am planning to make a middle layer between client and server ultimately (which is far from done of course).
